<?php
/**
 * Created by PhpStorm.
 * User: 牛旺科技
 * Date: 2019/7/24
 * Time: 11:15
 */

namespace app\index\controller;


use think\Controller;

class Base extends Controller
{

    public $user_info=[];

    public $uid;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $token = $_SERVER['HTTP_TOKEN'];
        $token = isset($_SERVER['HTTP_TOKEN'])?$_SERVER['HTTP_TOKEN']:$_REQUEST['token'];
        $user_id = input('post.token_uid',0);
        if(!$user_id) {
            $user_id = input('get.token_uid',0);
        }
        $this->user_info = token_verify($token,$user_id);
        $this->uid = $user_id;

        if(!$this->user_info) {

            $return = my_return('token:'.$token.'uid:'.$user_id,401,'登录已失效');
            echo  json_encode($return);
            die;
        }
    }


}